# Compile configuration
DMD ?= dmd
DEBUGFLAGS ?= -g -debug
RELEASEFLAGS ?= -O -release -noboundscheck

OUTPUTDIR ?= lib
LIBEXT ?= a

LINKERFLAGS ?= $(LDFLAGS)

COMMONFLAGS = -lib -Idirk -Idirk/libev -w -wi -de $(LINKERFLAGS) $(DFLAGS)

# Targets
DEBUG_NAME = $(OUTPUTDIR)/diggler-d.$(LIBEXT)
RELEASE_NAME = $(OUTPUTDIR)/diggler.$(LIBEXT)

.PHONY: debug release clean

all: debug release

debug: $(DEBUG_NAME)
release: $(RELEASE_NAME)

$(DEBUG_NAME): $(SOURCES)
	$(DMD) $(DEBUGFLAGS) $(COMMONFLAGS) -of$(DEBUG_NAME) $(SOURCES)

$(RELEASE_NAME): $(SOURCES)
	$(DMD) $(RELEASEFLAGS) $(COMMONFLAGS) -of$(RELEASE_NAME) $(SOURCES)

clean:
	rm $(DEBUG_NAME)
	rm $(RELEASE_NAME)

# Automatically generated by list_sources.d
SRC__SOURCES = \
	src/diggler/attribute.d \
	src/diggler/bot.d \
	src/diggler/bottracker.d \
	src/diggler/command.d \
	src/diggler/commandqueue.d \
	src/diggler/context.d \
	src/diggler/defaultcommands.d \
	src/diggler/eventloop.d \
	src/diggler/util.d

SOURCES = $(SRC__SOURCES)
